# Generated by Django 4.2.18 on 2025-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestForAbit', '0002_userpasses_userprogress_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('id_group', models.IntegerField()),
                ('list_prof', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField()),
                ('id_ques', models.IntegerField()),
                ('id_group', models.IntegerField(blank=True)),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField()),
                ('id_ques', models.IntegerField()),
                ('id_answ', models.IntegerField()),
                ('id_id_weights', models.IntegerField()),
                ('id_group', models.IntegerField(blank=True)),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField()),
                ('id_weight', models.IntegerField()),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
    ]
