# Generated by Django 4.2.18 on 2025-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestForAbit', '0004_alter_questions_id_group_alter_testanswers_id_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasses',
            name='id',
        ),
        migrations.AddField(
            model_name='userpasses',
            name='user_id',
            field=models.CharField(default='1234', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user_id',
            field=models.CharField(),
        ),
    ]
