# Generated by Django 4.2.18 on 2025-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestForAbit', '0003_listprof_questions_testanswers_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='id_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
